#!/usr/bin/env python3
"""
Sovereign Status Generator
Operation First Light - Sovereign Dashboard
Protocol OMNI v16.2.5

Queries Mem0 for memory count and nvidia-smi for GPU status.
Outputs sovereign_status.md report.
"""
import subprocess
import json
import datetime
import urllib.request
import urllib.error

def get_memory_count():
    try:
        req = urllib.request.Request(
            "http://localhost:8050/v1/memories/?user_id=sovereign",
            method="GET"
        )
        with urllib.request.urlopen(req, timeout=10) as response:
            data = json.loads(response.read().decode())
            if isinstance(data, list):
                return len(data), data
            elif isinstance(data, dict) and "memories" in data:
                return len(data["memories"]), data["memories"]
            else:
                return 0, []
    except urllib.error.HTTPError as e:
        return -1, f"HTTP Error: {e.code}"
    except urllib.error.URLError as e:
        return -1, f"Connection Error: {e.reason}"
    except Exception as e:
        return -1, str(e)

def get_gpu_status():
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=name,memory.used,memory.total,utilization.gpu", "--format=csv,noheader,nounits"],
            capture_output=True,
            text=True,
            timeout=10
        )
        if result.returncode == 0:
            return result.stdout.strip()
        else:
            return f"Error: {result.stderr}"
    except FileNotFoundError:
        return "nvidia-smi not found"
    except Exception as e:
        return str(e)

def generate_report():
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    mem_count, mem_data = get_memory_count()
    gpu_status = get_gpu_status()
    
    report = f"""# Sovereign Status Report

> **Generated**: {timestamp}
> **Protocol OMNI**: v16.2.5

---

## Health of the Mind (Memory Layer)

| Metric | Value |
|--------|-------|
| **Mem0 Service** | `http://localhost:8050` |
| **Memory Count** | {mem_count if mem_count >= 0 else 'ERROR'} |
| **Status** | {'HEALTHY' if mem_count >= 0 else 'DEGRADED'} |

"""
    if mem_count > 0 and isinstance(mem_data, list):
        report += "### Recent Memories\n\n"
        for i, mem in enumerate(mem_data[:5]):
            if isinstance(mem, dict):
                memory_text = mem.get("memory", mem.get("text", str(mem)))[:100]
                report += f"- `{memory_text}...`\n"
        report += "\n"

    report += f"""---

## Health of the Body (GPU Subsystem)

| GPU | Memory Used | Memory Total | Utilization |
|-----|-------------|--------------|-------------|
"""
    
    for line in gpu_status.split('\n'):
        if line.strip():
            parts = [p.strip() for p in line.split(',')]
            if len(parts) >= 4:
                report += f"| {parts[0]} | {parts[1]} MiB | {parts[2]} MiB | {parts[3]}% |\n"
            else:
                report += f"| {line} | - | - | - |\n"

    report += f"""
---

## System Verdict

**Cognitive Status**: {'SOVEREIGN' if mem_count >= 0 else 'IMPAIRED'}
**Inference Status**: {'OPERATIONAL' if 'Error' not in gpu_status else 'DEGRADED'}

*Generated by Operation First Light - Sovereign Dashboard*
"""

    with open("sovereign_status.md", "w") as f:
        f.write(report)
    
    print(f"Report saved to sovereign_status.md")
    print(f"Memory Count: {mem_count}")
    print(f"GPU Status: {gpu_status}")

if __name__ == "__main__":
    generate_report()
